//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATrackingAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemDetail
    {
        public string ItemID { get; set; }
        public string Desciption { get; set; }
        public string AdditionalDetail { get; set; }
        public Nullable<double> Price { get; set; }
        public string BudgetSource { get; set; }
        public string FiscalYear { get; set; }
        public string Group1 { get; set; }
        public string DAType1 { get; set; }
        public string DAType2 { get; set; }
        public string SupplierName { get; set; }
        public Nullable<System.DateTime> CheckInDate { get; set; }
        public string WarrantyYear { get; set; }
        public Nullable<System.DateTime> WarrantyExpiredDate { get; set; }
        public string ImagePath { get; set; }
        public string ImportSource { get; set; }
    }
}
