//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATrackingAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemTracking
    {
        public string ItemID { get; set; }
        public Nullable<System.DateTime> VerifiedDate { get; set; }
        public string FiscalYear { get; set; }
        public string Note { get; set; }
        public string Location { get; set; }
        public string Owner { get; set; }
        public string ConditionID { get; set; }
        public string StatusID { get; set; }
        public Nullable<System.DateTime> CommittedDate { get; set; }
    }
}
